### ISSUE TITLE
/api/speedtest/service/stat - Status 400

### ISSUE THREAD

**Issue by a-bianucci** [mihakralj/opnsense-speedtest#15]
When making the API call for the above - get an action stat not found.

Can do the /api/speedtest/service/run and that returns 200 which is expected.

Error in logs
`Script action failed with Command '/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/speedtest/opn_speedtest.py ''' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 482, in execute subprocess.check_call(script_command, env=self.config_environment, shell=True, File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/speedtest/opn_speedtest.py ''' returned non-zero exit status 1.`

**Comment by mihakralj** [comment]
Speedtest plugin was absorbed into https://github.com/mimugmail/opn-repo over a year ago... :) Check the latest version in that repo, this one on my Github account is several versions behind current and not updated.

**Comment by I-Would-Like-To-Report-A-Bug-Please** [comment]
> Speedtest plugin was absorbed into https://github.com/mimugmail/opn-repo over a year ago... :) Check the latest version in that repo, this one on my Github account is several versions behind current and not updated.

Maybe archiving repo and updating README would help?
